//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserNameAvailablity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student
    {
        public int StudId { get; set; }
        public string StudName { get; set; }
        public string StuPassword { get; set; }
    }
}
